### ISSUE TITLE
大佬 可不可以加上自动调度代理池的ip 然后配置到本地代理 然后如果本地配置的代理失效 再继续调度配置

### ISSUE THREAD

**Issue by koidnqewiu** [ydf0509/proxypool_framework#1]

**Comment by ydf0509** [comment]
conntrib 里面的ProxyClient就是自动重试自动切换使用代理了。

**Comment by koidnqewiu** [comment]
> 
> 
> conntrib 里面的ProxyClient就是自动重试自动切换使用代理了。

谢谢大佬 没仔细看 大佬有没有办法把这些代理部署到网站服务器上  部署一个反向代理 如果代理不能用的话 也可以自动切换

**Comment by ydf0509** [comment]
> > conntrib 里面的ProxyClient就是自动重试自动切换使用代理了。
> 
> 谢谢大佬 没仔细看 大佬有没有办法把这些代理部署到网站服务器上 部署一个反向代理 如果代理不能用的话 也可以自动切换

你可以自己弄，就是代理设置为一个固定的 falsk ip:port，然后peoxies设置为这个flask的端口是吧。这样有个弊端，所有请求都走这台flask机器转发一下，有带宽限制。 proxyClient是自动的，request方法 已近兼容了requests.request的所有入参了，并不需要改入参，用就是了。搞那个花里胡哨再转发一下没用，反而还降低性能和稳定了。

**Comment by koidnqewiu** [comment]
大佬 我有些看不懂 我是没学过代码 完全找的一键端搭建的网站 用的nginx和php  你的意思就是 是不是用proxyClient配置的代理 和反向代理的作用一样 如果我用了高匿名代理 别人是不是同样也ping不到我的真实ip
