### ISSUE TITLE
安装后无法运行

### ISSUE THREAD

**Issue by ByteStardust** [ydf0509/proxypool_framework#2]
Linux ubuntu20
Python 3.11 python3.8
运行报错没有包 nb_log_config
已确认安装此包
![image](https://user-images.githubusercontent.com/32776949/205705944-7752b68b-97b7-42cd-92b3-076fc3f19049.png)

**Comment by ydf0509** [comment]
![image](https://user-images.githubusercontent.com/26890690/205784242-a08039e7-b78b-4951-bf1a-52b6e46a8a41.png)


你肯定没按照教程 python -m 运行，也不知道什么叫PYTHONPATH

**Comment by ByteStardust** [comment]
运行起来了，发现没一个可用，好久都没维护了😂

**Comment by ydf0509** [comment]
> 运行起来了，发现没一个可用，好久都没维护了😂

我早就知道这一点了，里面的代理网站全部倒闭了。需要你自己找网站写解析函数。这个是提供代理池框架，函数是框架附赠的，需要用户自己写。

**Comment by ydf0509** [comment]
> > 运行起来了，发现没一个可用，好久都没维护了😂
> 
> 我早就知道这一点了，里面的代理网站全部倒闭了。需要你自己找网站写解析函数。这个是提供代理池框架，函数是框架附赠的，需要用户自己找网站写解析函数。

**Comment by ByteStardust** [comment]
明白了，我研究研究代码，添加动态代理功能实现简单快速高并发
